### ISSUE TITLE
Issue raised in the NineBreakHomePage project: java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/CompareDirectoriesGradlePlugin#25]
https://github.com/kazurayam/NineBreakHomePage/issues/55

**Comment by kazurayam** [comment]
I found that the test case was trying to make a text diff of a PDF file when it threw the MalformedInputExeption:

<img width="832" alt="スクリーンショット 2023-04-05 23 17 51" src="https://user-images.githubusercontent.com/4467417/230109369-b4f1b49c-19ab-4dbb-92f3-ddb72b35419d.png">

Well, the code was just incomplete.

**Comment by kazurayam** [comment]
When the file was NOT a text but binary, then a diff file with the following text should be produced.

```
--- /Users/kazurayam/katalon-workspace/KS_versions_source_diff/build/source/8.4.1/home/pdf/1355362027.pdf
+++ /Users/kazurayam/katalon-workspace/KS_versions_source_diff/build/source/8.6.0/home/pdf/1355362027.pdf

Unable to make diff as this is not a text
```

**Comment by kazurayam** [comment]
v0.1.8, [Issue25Test](https://github.com/kazurayam/CompareDirectoriesGradlePlugin/blob/0.1.8/plugin-project/plugin/src/test/groovy/com/kazurayam/dircomp/Issue25Test.groovy) failed

```
Assertion failed: 

assert Files.exists(dirA)
             |      |
             false  ../../../NineBreakHomePage/site/build/tmp/snapshot

	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:432)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
	at com.kazurayam.dircomp.Issue25Test.setup(Issue25Test.groovy:38)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	
```

The NineBreakHomePage project changed a bit, so the directory is not there.

I will put `@Disable` annotation to this test class.
