### ISSUE TITLE
On Windows, DirectoryComparator#toSubPaths(Path, Set<Path>) threw Exception: java.lang.IllegalArgumentException: 'other' is different type of Path

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/CompareDirectoriesGradlePlugin#54]
at  https://github.com/kazurayam/CompareDirectoriesGradlePlugin/blob/0.2.2/plugin/src/test/groovy/com/kazurayam/dircomp/DirectoriesComparatorTest.groovy

```
test_toSubPaths()

java.lang.IllegalArgumentException: 'other' is different type of Path
	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:400)
	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
	at java_nio_file_Path$relativize$2.call(Unknown Source)
	at com.kazurayam.dircomp.DirectoriesComparator$_toSubPaths_closure3.doCall(DirectoriesComparator.groovy:91)
```

**Comment by kazurayam** [comment]
On Mac, I did not see this type of error.

**Comment by kazurayam** [comment]
added a debug printing:
```
   static Set<String> toSubPaths(Path dir, Set<Path> paths) {
        Set<String> set = new HashSet<>()
        paths.each {path ->
            
            System.out.println("dir : " + dir)
            System.out.println("path: " + path)
            
            set.add(dir.relativize(path).toString())
        }
        return set
    }
```

I got this result:

```
dir : \Users\uraya\github\CompareDirectoriesGradlePlugin\plugin\test-output\com.kazurayam.dircomp.DirectoriesComparatorTest\A
path: C:\Users\uraya\github\CompareDirectoriesGradlePlugin\plugin\test-output\com.kazurayam.dircomp.DirectoriesComparatorTest\A\e.txt
```

It's naive.
